org: org
app: app
service: service

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.8
  memorySize: 1024

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /
          method: get
